version: '3'
services:
  jupyter:
    image: italianai
    build: 
      context: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # alternatively, use `count: all` for all GPUs
              capabilities: [gpu]
    volumes:
      - ~/doc:/usr/src/app/doc
    ports:
      - 8888:8888
    command: "jupyter notebook --ip 0.0.0.0 --no-browser"